apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: kubedb:core:edit
rules:
- apiGroups:
  - kubedb.com
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - catalog.kubedb.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
