apiVersion: v1
data:
  tls.crt: LS0tLS1C
  tls.key: LS0
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb
    app.kubernetes.io/version: v0.15.1
    helm.sh/chart: kubedb-v0.15.1
  name: kubedb-apiserver-cert
  namespace: default
type: Opaque
