apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded,hook-failed
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb
    app.kubernetes.io/version: v0.15.1
    helm.sh/chart: kubedb-v0.15.1
  name: kubedb-cleaner
  namespace: default
spec:
  activeDeadlineSeconds: 120
  backoffLimit: 3
  template:
    spec:
      containers:
      - command:
        - sh
        - -c
        - sleep 2; kubectl delete validatingwebhookconfigurations validators.kubedb.com
          || true; kubectl delete mutatingwebhookconfiguration mutators.kubedb.com
          || true; kubectl delete apiservice v1alpha1.mutators.kubedb.com || true;
          kubectl delete apiservice v1alpha1.validators.kubedb.com || true;
        image: appscode/kubectl:v1.16
        imagePullPolicy: IfNotPresent
        name: busybox
      restartPolicy: Never
      serviceAccountName: kubedb
