apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb
    app.kubernetes.io/version: v0.15.1
    helm.sh/chart: kubedb-v0.15.1
  name: validators.kubedb.com
webhooks:
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/elasticsearches
  failurePolicy: Fail
  name: elasticsearch.validators.kubedb.com
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - elasticsearches
  sideEffects: None
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/postgreses
  failurePolicy: Fail
  name: postgres.validators.kubedb.com
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - postgreses
  sideEffects: None
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/mysqls
  failurePolicy: Fail
  name: mysql.validators.kubedb.com
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - mysqls
  sideEffects: None
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/perconaxtradbs
  failurePolicy: Fail
  name: perconaxtradb.validators.kubedb.com
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - perconaxtradbs
  sideEffects: None
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/mongodbs
  failurePolicy: Fail
  name: mongodb.validators.kubedb.com
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - mongodbs
  sideEffects: None
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/redises
  failurePolicy: Fail
  name: redis.validators.kubedb.com
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - redises
  sideEffects: None
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/memcacheds
  failurePolicy: Fail
  name: memcached.validators.kubedb.com
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - memcacheds
  sideEffects: None
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/etcds
  failurePolicy: Fail
  name: etcd.validators.kubedb.com
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - etcds
  sideEffects: None
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/pgbouncers
  failurePolicy: Fail
  name: pgbouncer.validators.kubedb.com
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - pgbouncers
  sideEffects: None
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/proxysqls
  failurePolicy: Fail
  name: proxysql.validators.kubedb.com
  rules:
  - apiGroups:
    - kubedb.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - proxysqls
  sideEffects: None
- clientConfig:
    caBundle: bm90LWNhLWNlcnQ=
    service:
      name: kubernetes
      namespace: default
      path: /apis/validators.kubedb.com/v1alpha1/namespaces
  failurePolicy: Fail
  name: namespace.validators.kubedb.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - '*'
    operations:
    - DELETE
    resources:
    - namespaces
  sideEffects: None
